\documentclass[final,t]{beamer}
\mode<presentation>{\usetheme{I6dv}}

% additional settings
\setbeamerfont{itemize}{size=\normalsize}
\setbeamerfont{itemize/enumerate body}{size=\normalsize}
\setbeamerfont{itemize/enumerate subbody}{size=\normalsize}

% additional packages
\usepackage{xcolor}
\usepackage{times}
\usepackage{amsmath,amsthm, amssymb, latexsym}
\usepackage{exscale}
\usepackage{subfig}
\usepackage{booktabs, array}
\usepackage{tabularx}
\usepackage[english]{babel}
\usepackage[latin1]{inputenc}
\usepackage[orientation=landscape,size=custom,width=21.59,height=27.94,scale=0.45]{beamerposter} % in cm, equal to 8.5" wide x 11" high
\listfiles

% Display a grid to help align images
%\beamertemplategridbackground[1cm]

\newcolumntype{R}{>{\raggedleft\arraybackslash}X}


\title{\Large 2019 Tampa Bay Water Quality Assessments}
\author{\normalsize A Tampa Bay Estuary Program Initiative to Maintain and Restore the Bay's Seagrass Resources}

\begin{document}

\begin{frame}

% \vspace{-0.6cm} %spacing for block distance from header
\begin{columns}[t]
% \hspace{0.4cm}

%%%%%%%%%%%%%%
% LEFT
%%%%%%%%%%%%%%
\begin{column}{.31\linewidth}

\begin{block}{First block}

\end{block}

\end{column}

%%%%%%%%%%%%%%
% CENTER
%%%%%%%%%%%%%%    
\begin{column}{.31\linewidth}

\begin{block}{Second block}

\end{block}

\end{column}

%%%%%%%%%%%%%%
% RIGHT
%%%%%%%%%%%%%%
\begin{column}{.31\linewidth}

\begin{block}{Third block}

\end{block}


\footnotesize \textit{\textbf{Acknowledgments}: Continuing water quality monitoring support provided by the Environmental Protection Commission of Hillsborough County.  Consulting support provided by Janicki Environmental, Inc.  Full methods provdided in Janicki, A., Wade, D., Pribble, R.J. 2000. \href{https://www.tbeptech.org/TBEP_TECH_PUBS/2000/TBEP_04_00Chlor-A.pdf}{TBEP Technical Report \#04\-00}.} \\

\end{column}

\end{columns}

\end{frame}

\end{document}
