on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
    
name: build 

jobs:
  render:
    name: build
    runs-on: windows-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: '3.5.3' # The R version to download (if necessary) and use.
    - run: Rscript -e 'print("hello")'