on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
    
name: build 

jobs:
  render:
    name: build
    runs-on: windows-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: '3.5.3' # The R version to download (if necessary) and use.
    - uses: r-lib/actions/setup-pandoc@v2
    - uses: r-lib/actions/setup-tinytex@master
    - name: Install dependencies
      run: |
        install.packages(c("dplyr", "knitr", "remotes", "rmarkdown", "ggmap", "ggsn", "ggrepel", "here", "tibble", "ggplot2", "gridExtra", "Hmisc", "tinytex", "pdftools", "git2r"))
        remotes::install_version('sf', version = '0.9-8')
        remotes::install_github('tbep-tech/tbeptools')
      shell: Rscript {0}
    - name: Build report card
      run: Rscript -e 'source("build.R")'
    - name: Commit results
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add -A
        git commit -m 'Re-build data' || echo "No changes to commit"
        git push origin || echo "No changes to commit"