on:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: "0 0 * * *"
    
name: build 

jobs:
  render:
    name: build
    runs-on: ubuntu-20.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
        with: 
          extra-repositories: 'https://tbep-tech.r-universe.dev'
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-tinytex@v2
      - name: Install ubuntu dependencies
        run: |
          sudo apt-get install libcurl4-gnutls-dev
          sudo apt-get install libcairo2-dev
          sudo apt-get install libxt-dev
          sudo apt-get install libssl-dev
          sudo apt-get install libssh2-1-dev
          sudo apt-get install libudunits2-dev
          sudo apt-get install libgdal-dev
          sudo apt-get install libgeos-dev
          sudo apt-get install libproj-dev
          sudo apt-get install libpoppler-cpp-dev
          sudo apt-get install libgit2-dev
      - name: Setup R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::dplyr
            any::knitr
            any::rmarkdown
            any::ggmap
            any::ggsn
            any::ggrepel
            any::here
            any::tibble
            any::ggplot2
            any::gridExtra
            any::Hmisc
            any::tinytex
            any::pdftools
            any::git2r
            any::sf
            tbeptools

      - name: Build report card
        run: Rscript -e 'source("build.R")'
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git commit -m 'Re-build data' || echo "No changes to commit"
          git push origin || echo "No changes to commit"